name: triana_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  chat_bubbles: ^1.7.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_modular: ^6.3.4
  gap: ^3.0.1
  lottie: ^3.3.1
  mqtt5_client: ^4.12.0
  serial: ^0.0.7+1
  web_blue: ^0.2.0
  # mqtt_client: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/assets/
    - assets/images/
